platzigram/platzigram/urls.py
# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

# temp for hello world
from platzigram import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # local urls
    path('local/hello-world/', views.hello_world, name='hello'),
    path('local/hi/<str:name>/<int:age>/', views.say_hi, name='hi'),
    path('local/sorted_ints/', views.sorted_ints, name='sorted_ints'),
    path('local/json_ints/', views.json_ints, name='json_ints'),
    # app urls
    path('', include('posts.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platzigram/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.PostsListView.as_view(), name='list_posts'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail_post'),
    path('posts/new/', views.CreatePostView.as_view(), name='create_post'),
]

platzigram/users/urls.py
# Django
from django.urls import path
# Views
from . import views

app_name = "users"

urlpatterns = [
    # User management
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),

    path('me/profile/', views.UpdateProfileView.as_view(), name='update_profile'),

    # About posts user
    path(
        route='@<str:username>/',
        view=views.UserDetailView.as_view(template_name='users/detail.html'),
        name='detail'
    ),
]

platzigram/posts/models.py
# Django
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    """Post model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/photos')

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return title and username."""
        return '{} by @{}'.format(self.title, self.user.username)

platzigram/posts/forms.py
# Django
from django import forms

# Models
from posts.models import Post

class PostForm(forms.ModelForm):
    """Post model form."""

    class Meta:
        """Form settings."""
        model = Post
        fields = ('user', 'profile', 'title', 'photo')

platzigram/posts/views.py
# Django
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView
# Forms
from .forms import PostForm
# Models
from .models import Post

# Views
class PostsListView(LoginRequiredMixin, ListView):
    """Return all published posts."""

    template_name = 'posts/feed.html'
    model = Post
    ordering = ('-created',)
    paginate_by = 2
    context_object_name = 'posts'

class PostDetailView(LoginRequiredMixin, DetailView):
    """Post detail view."""

    template_name = 'post/detail.html'
    queryset = Post.objects.all()
    context_object_name = 'post'

class CreatePostView(LoginRequiredMixin, CreateView):
    """Create a new post."""

    template_name = 'posts/new.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:list_posts')

    def get_context_data(self, **kwargs):
        """Add user and profile to context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile
        return context

platzigram/posts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
</head>
<body>
    {% include "nav.html" %}
    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>
</body>
</html>

platzigram/posts/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" href="{% url 'posts:list_posts' %}" style="border-right: 1px solid #efefef;">
            <img src="{% static 'img/instagram.png' %}" height="45" alt="logo platzigram" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url 'users:detail' request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" alt="profile picture" class="d-inline-block align-top rounded-circle" />
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" height="35" alt="default img profile" class="d-inline-block align-top rounded-circle" />
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create_post' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

platzigram/posts/templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Previous
            </a>
        </li>
    {% endif %}

    <li class="page-item">
        <a class="page-link" href="#">
        {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </a>
    </li>

    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Next
            </a>
        </li>
    {% endif %}
    </ul>
</nav>